### PR TITLE
Fix version

### LINKED ISSUE #1: LCD init lib
Include in menu Liquid Crystal Base library

### LINKED ISSUE #2: Change menu allocation to pointers
EncMenu update generation of screen/lines

### PR DESCRIPTION
**Pull request by IgorIoT13**

### CODE REVIEW

File: Enc.h [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    else if(en.rightH()){
+      if(menu.curr == Heat && TargetTemp < 60){
+        updateTemp = true;
+        TargetTemp += 1;
+        Serial.println(TargetTemp);
+      }
+    }
+
+    else if (en.left()) {
+        enc_pre = 0x03;
```
Comment (VladVanyuk) [inline Enc.h]: What does this flag do? 
Name them

File: btns.h [hunk 2]
```diff
@@ -7,21 +7,35 @@
 #include "settings.h"
 #include "relay.h"
 
+
+bool fan = false;
```
Comment (VladVanyuk) [inline btns.h:11]: fan_active_fl

File: Enc.h [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+void encoder_setup(){
+  en.setEncType(EB_STEP4_LOW);
+  en.setBtnLevel(HIGH);
+}
+
+int getResult(){
+  return enc_pre; 
+}
+
+bool flagEnc = false;
```
Comment (VladVanyuk) [inline Enc.h]: What purpose of this?

File: debug_helper.h [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+#define DEBUG_HELPER
+
+#include <Arduino.h>
+
+
+#define DEBUG_MODE
+
+#define INFO_WIFI
+
+void debugMeseg(char* meseg){
```
Comment (VladVanyuk) [inline debug_helper.h:11]: Chenge to macros

File: tempSensor.h [hunk 5]
```diff
@@ -32,6 +35,9 @@ float readSensorComplete()
 
 float readSensor()
 {
+    #ifdef DEBUG_FUNC
+      Serial.println(__func__);
+    #endif
 #if(VIRT_SENSOR == 0)
```
Comment (VladVanyuk) [inline tempSensor.h:41]: delete all examples of this define

File: menu.h [hunk 6]
```diff
@@ -58,17 +62,27 @@ STATUS_t initSection() {
     } else {
       return FAILURE;
     }
+
+  footerLine = initLine( "Timer: ", "Timer", NULL);
+  footerLine->val->setChar(footerLine->val, "");
```
Comment (VladVanyuk) [inline menu.h:67]: Double check this functionality. You are parsing a pointer to a char array to the pointer of char

**Review by VladVanyuk — APPROVED** [review]
Change what i said in comments

File: Enc.h (hunk 3 above)
Comment (VladVanyuk) [reply Enc.h]: Same flag as in prev issue? 
@IgorIoT13  @olehdzhufer

File: debug_helper.h (hunk 4 above)
Comment (VladVanyuk) [reply debug_helper.h:11]: @IgorIoT13

File: tempSensor.h (hunk 5 above)
Comment (VladVanyuk) [reply tempSensor.h:41]: @olehdzhufer @olegdzhufer

**Comment by VladVanyuk** [comment]
@IgorIoT13 @olehdzhufer @olegdzhufer

File: Enc.h (hunk 1 above)
Comment (VladVanyuk) [reply Enc.h]: @ @olehdzhufer @olegdzhufer

File: btns.h (hunk 2 above)
Comment (VladVanyuk) [reply btns.h:11]: @IgorIoT13 @olehdzhufer @olegdzhufer
